# Generated by Django 2.2.5 on 2020-03-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190416_0149'),
        ('blog', '0002_auto_20200219_1914'),
    ]

    operations = [
    ]
